#!/usr/bin/env python
# coding=utf-8



customFormatsClassic = [
    r'Titilo: %TAutores: %ARevista: %JVolumen: %vPagina: %pAnho: %YResumen: %BCitas: %cURL: %uAffiliations:%F',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%G: %T,  %Y, %j,  {\\bf %v}, %p-%P',
    r'\\bibitem[%\4m%(y)]%{R} %\5.1l %\t. %\j %\V,%\p%-\P\ (%\Y) ',
    r'%\z120 \\item {\\it %\T} \\\\  %\l %\Y,%\j,%\V,%\p \\\\',
    r'%L %(y) "%T", %q, %V, %p-%P\.',
    r'%J\t%T\t%N\t%D\t%Y\t%V\t\t\t\t%p%\(-)P',
    r'%g, %T, %J, %V, %p, %D',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{%1H%\y} %\5.3l %\Y,%\j,%\V,%\p',
    r'<A HREF="%u">"%T"</A>, %L %Y,%q,%v,%p <P>',
    r'%\5.3l %\Y,%\j,%\V,%\p citations=%\5.3c',
    r'\\bibitem{%\1H\:%\yab}"%\T\,'' %\7I,%\j {\\bf %\V}, %\p-%\P %(y).\\textrm{(E)} ',
    r'%10G , %"T," %J , %V, %(y)',
    r'%u:%c',
    r'%z1%10i %(Y), %T,%\J,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R} %\100l %\Y,%\j,%\V,%\p',
    r'%8.l %J, %V, %p, %y, %d ',
    r'%8.8l, %\t, %\Y, %\q, %\V, %\p',
    r'\\bibitem[%\4m%(y)]%{L} %\8l %\Y,%\j,%\V,%\p',
    r'%T%a%Q,%V,pp. %P-%p, %Y ',
    r'%\T,%\6za2, %\Y,%\J,%\V,%\p [%\c]',
    r'\\item  %\8i (%\Y). %\T. %\j,%\V,%\p  (%\c citations)',
    r'\\bibitem%{R} %\5.3i %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R} %\3l %\Y,%\j,%\V,%\p,%\X,%\T',
    r'%g %Y, "%t," %j, %V, %p',
    r'%i %(y), %T,%q,%V,%p%-P\, doi:%d.',
    r'%8.8l, %\t, %\Y, %\q, %\V, %\p',
    r'\\bibitem[%\4m%(y)]%{R} %\10.3l %\Y,%\j,%\V,%\p',
    r'%\7g %\y. %T%\j %\V:%\p--%\P',
    r'%10I %Y.%t.%J %V,%p%-P.',
    r'%{T} %\99I,%\j %\V,%\p,%(Y)',
    r'\\reference{} %\8l %\Y,%\j,%\V,%\p',
    r'"%T" %\8l %\Y,%\j,%\V,%\p\\',
    r'%1l %\Y,%\q,%\V,%\p',
    r'\\bibitem[{{%\3m}%(y)}]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'\\item \href{%u}{%\R} %\I: \textit{%\T,} %\j,%\V,%\p %(y)',
    r'%a,%Y,"%T", %q,%V,%p',
    r'\\bibitem%{n%R} %\8I,  %\J \{\\bf %\V\}, %\p %(\Y). \[%X\].',
    r'%ZEncoding:UTF-8 %ZEOL:"" \\bibitem\%{%1H%Y}%z0 %\g, %Y, \ewblock \\emph{%T,} \ewblock %J, %V, %p  \ewblock {\\bf [citations=%c]}',
    r'%i%T%q %v %p-%P%Y',
    r'%A, %T, %J, %V, %p, (%Y)',
    r'%5l %Y, "%t'', {\\it %J}, {\\bf %V}, %p',
    r'<li>%4G,<br>%T<br>%U</li>',
    r'\\item %\8.3g,%\Y,"%\t", %\q, % \V, % \p',
    r'\\bibitem[%\2M%(y)]%{R} %\10i (%\Y),%\t,%\j,%\({\\textit )V\(}, )%\p%-\P,\\doi{%\d}\.',
    r'\\item{%\l %\Y,"%\T",%\J,%\V,%\p}',
    r'%Y %q %V p%p-%P, %T,  %G ',
    r'\\bibitem%[N]%{R} %2l %Y,%j,%V,%p',
    r'%z0%a%T%J,%Y:%V:%p-%P  ',
    r'"%T",%L,%q,%V,%p-%P %(y)',
    r'\\item %\l %\Y,%\j,%\V,%\p',
    r'%L %Y.%t.%J %V,%p-%P.',
    r'%3M.%T.%j%(Y)',
    r'\\bibitem%{R} \t%2N\t%\N\t%\T\t%\Y\t%\j\t%\V\t%\p\t\citas%\c\t%\d',
    r'%%%% %T %%%% %u \\bibitem[%\3m%(y)]{%\1h:%\Y} %\8l~%\Y,%\j,%\V,%\p',
    r'%%%% %T %%%% %u \\bibitem[%\3m%(y)]{%\1h:%\Y} %\l~%\Y,%\j,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R} %\1500.10A %\Y,%\j,%\V,%\p',
    r'%1l %\Y,%\q,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R}{%\8l %\Y, "%\T'', %\j, \\textbf{%\V}, %\p--%\P}',
    r'%g %Y, %q, %V, %p %P, "%T"',
    r'%ZEncoding:UTF-8%>: %z0  %T;rus auth;%g;wos id;copus id;%Y;%K;%W;%J;ISSN;e-ISSN;ISBN;v.%V p.%p-%P;%D;%d;wos;scopus;https://arxiv.org/pdf/%X;;;;;;;;;;;;;;;%R;%u',
    r'%I,%Y, "%T", %J% V%, p-%P. [%R]',
    r'%l %Y, %J v.%V, pp. %p-%P; "%T"',
    r'\\bibitem[%\3m(%\y)]{%\h%\y} %\8l %\Y, "%\t,'' %\j,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{za1%\Y} %\5.3l %\Y,%\j,%\V,%\p',
    r'%4M,%Y,%q,%v,%p',
    r'%\I (%\D). %\T %\q %\V, %\p-%\P.',
    r'\\bibitem[%\4m%(y)]%{R}%\10.3g %\Y,%T,%\j,%\V,%\p',
    r'%i.%Y.%T.%J %V:%p%-P.',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\T,%\j,%\V,%\p',
    r'%%%% %T %%%% %u \\bibitem[%\3m%(y)]{%\1h:%\Y} %\8l~%\Y,%\j,%\V,%\p',
    r'\\bibitem[%\2m%(y)]%{R} %\l %\Y,%\(\ ") T\('', ) %\j,%\V,%\p ',
    r'%\8l %\Y,%\j, %t, %\V, %\p',
    r'%\3.2m %(y) %t  %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\2m%(y)]%{R} %\l %\Y,%\(\\emph{ ) T\(}, ) %\j,%\V,%\p,%u.',
    r'\\bibitem%N %8a ,%T,%R,%j,%V,%P',
    r'* \\bibitem[%3M (%Y)]{%za1%Y} {%10L} %Y, \\textit{%J}, %V, %p',
    r'\\bibitem[%\2m%(y)]%{za1%Y}  %\5l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R} %\99.3l, %\({\\it )t\(},) %\Y,%\j,%\V,%\p',
    r'Author, date. Title. Journal Volume Pages',
    r'%G,%T,%J,%V,%p,%Y',
    r'%Zencoding:ISO-8859-1 %z0%g*%T*%Q*%Y*%R*%u ',
    r'\\item\{ %\10I. (%\Y): \\emph\{%\T\}. \{\\em %\J\}, \\underline{%\V}:%\p%-\P % \X\}',
    r'%Y %c \XX %6.6M %z150',
    r'%A %(y) %T. %J, %\V,%\p',
    r'%I %\Y,%\j,%\V,%\p%T',
    r'\\bibitem[%\4m%(y)]%{R} %\I %\Y,%\j,%\V,%\p',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R} %>100.100I,%>Y.%>J, %>V,%\p',
    r'"%T", %A,(%D), %Y,%q %V,%p.',
    r'%5.1a,%t,%q,%J,%V,%p-%P,%Y',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'%8.3g,%Y,%q, %V,%\p',
    r'\\reference{} %\8l %\Y,%\j,%\V,%\p',
    r'#ItemStart#%r#%T#%3m#%J#%V#%p#%y#',
    r'\\reference{} %\8l %\Y,%\j,%\V,%\p',
    r'[%4m%(y)]%{R} %8l %Y,%j,%V,%pn',
    r'%4l %Y,%J,%V,%p',
    r'\\bibitem[%\1m%(y)]%{R} %\3.3l %\Y,%\J,%\V,%\p',
    r'\\bibitem[%\4m%(y)]{%\1h%y}%l\\ %y\\,"%T\," %\j,%V,%p',
    r'%\8.3g,%T,%\Y,%\q, %\V,%\p Number of citations: %\c ',
    r'%L  "%T",  %Y, %J, citations: %c',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p,%\P',
    r'%ZEncoding:UTF-8 \[%zn\] %8.4g,%t,%Y,%q, %V,%p%-P',
    r'\\bibitem[%\4m%(y)]%{R} %\5.100l %\Y,%\j,%\V,%\p%u',
    r'%Zencoding:UTF-8\@R %R _FIELDEND_\@T %T _FIELDEND_\@a %a _FIELDEND_\@F %F _FIELDEND_\@J %J _FIELDEND_\@j %j _FIELDEND_\@Q %Q _FIELDEND_\@q %q _FIELDEND_\@V %V _FIELDEND_\@P %P _FIELDEND_\@p %p _FIELDEND_\@D %D _FIELDEND_\@Y %Y _FIELDEND_\@d %d _FIELDEND_\@c %c _FIELDEND_\@u %u _FIELDEND_\@W %W _FIELDEND_\@S %S _FIELDEND_\@B %B _FIELDEND_\@K %K _FIELDEND_\@x %x _FIELDEND__RECORDEND_',
    r'%\g,"%\T" // %\J, V. %\v,Pp. %\p-%\P (%\Y)',
    r'%G %Y,<i>%q</i>, %V,%p,%T, %U<br />   <br /><br />',
    r'%g %y. %t.%J %v,%p-%P.%p.  ',
    r'\\bibitem[%\2M%(y)]%{R} %\8l. %\T.%\j %\V,%\p%-\P\.(%\Y).',
    r'%z000%G (%Y), %J %V, %p%-P. "%t"',
    r'%1.3l  %c',
    r'%\I, %J  \{\\bf %V\}, %p %(y).',
    r'%Zencoding:UTF-8%Zlinelength:1024"%t", %g %y, %J %v,%p',
    r'%1G,%Y,%q,%v,%p:"%t"',
    r'%- I %\T %J%,V%,p%,y%u',
    r'%\W<p><a href=%>u>"%>T"</a>,</p><p class="tab">%>15.8i: %>Y,%>J,%>V,%>p</p>',
    r'%\8N %\Y,%\J,%\V,%\p-%\P\\\\%\t',
    r'\\bibitem%{R} %\I %\Y.%\t.%\j \\ %\V,%\p%-\P\ %u .',
    r'%z500%y |%3.3g |%t  |%j | %v|%p  |%u  ',
    r'\\bibitem[%\2m%(y)]%{za1%y} %\8l %\Y,%\j,%\V,%\p',
    r'%5.3l (%Y),%j,%V,%\p',
    r'%\T|%1.3G|%\Y|%\q|%\V|%\p|%\d',
    r'%ZEncoding:TeX\\bibitem %L %Y, {\\it %T}, %q, %v, %p---%P',
    r'%T,%a,%y,%j,%V,%p',
    r'\\item %\12.12N, %y, \"%\T\", \{\\em %\J\}, %\V\, %\p',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R} %\8.3g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[\\protect\\citeauthoryear{%\2M}{%y}]{%za1%y}  %\G,%\j \\ \\textbf{%\V} %\p (%\Y)',
    r'%\M  %\F',
    r'%u',
    r'[%W %(y)] %3l , %Y, %t, %J , \Volume %\V , \Page %\p , DOI: %d ',
    r'(%zn) %3I%J, %V, %p-%P (%Y)%Tpublication type: %W (cited %c times)adscode: %R',
    r'\\refs %\3.3l %(y) %\t.\{\\em %\j,%\V\}, %\p-%\P\.',
    r'%ZEncoding:UTF-8 %z0%g*%T*%Q*%Y*%R*%u ',
    r'%10.1l || %y || %T || %J || %v || %p || %d || %c || %l  ||',
    r'%L  %\7.3t  %y, %j, %v, %p  %u ',
    r'\\bibitem[%\1h(%y)]%{za1%\Y} %\8.50g, %\Y, %\q, %\V, %\p',
    r'%\l, %\Y, %\j, %\V, %\p, %\t',
    r'\\bibitem{%za1%y} %5a. %T. {\\it %J} {\\bf %V}, %p-%P (%y).',
    r'{\\bf Title: %\t\\\\}{\\bf Authors}: %\3.3m\t%\r \\vspace\*{0.1cm}\\\\{\\bf Abstract:} %\B\\vspace\*{0.3cm}%%-----------------------',
    r'%\8l %T %Y,%\J,%\V,%\p',
    r'%\l %\Y, "%\t,\" %\j,%\V,%\p',
    r'AASTeX',
    r'%i.%Y.%T.%J %V:%p%-P.',
    r'%\2G,"%T", %\Y,%\J,%\V,%\p,%\U',
    r'http://ching5696@adsabs.harvard.eduhttp://ching5696@adsabs.harvard.edu/about489@adsabs.harvard.edu',
    r'%\80l, "%\T", %\Y,  %\J %\V,%\p-%\P..',
    r'%6.1m "%T", %Y,%j,%V,%p',
    r'\\bibitem[%\2m%(y)]{%h%y}\\textsc{%\8l\\;} (%\Y).{\\em %T},%\j\\ %\V, %\p--%P\\ads{%>u}',
    r'\\item  %\i (%\Y). %\T. %\j,%\V,%\p  (%\c citations)',
    r'\\bibitem[%\4m%(y)]%{R} %\8i %\Y, %"T", %\j,%\V,%\p',
    r'%\10I,(%Y),%t,%J,%V,%\p%-\P',
    r'%\5l\(\\ ") % \T\" %\Y,%\j,%\V,%\p',
    r'\oindent %\8l %\Y,%\t,%\j,%\V,%\p',
    r'%I (%Y) %T. %J %V,%p%-%P\. doi:%d %z999',
    r'%ZEncoding:TeX %z75\\item %N,%Y,%\(")T\('', )\{\\em %J\}, \{\\bf %V\}, %p--%P (%c citations; journal impact factor XX) \\\\',
    r'%z132 \\bibitem[%\2m%(y)%\3m]%{R}   %\8.1g,     %\Y,%\q,%\V,%\p',
    r'%\8l %\T, %\Y,%\J,%\V,%\p',
    r'%N,%Y,%J,vol %V%\(, page )p%\(-)P %(x)%\(\\\\ {\\it )T\(})',
    r'%5.3l %y,%q,%v,%p',
    r'%ZEncoding:UTF-8[%zn]|%I|%T|%J|%V, %p (%Y)|%D|%R',
    r'%3L, "%T," %q, %V, %P, (%Y).',
    r'%L,%"T'',%y,%J,%V,%p',
    r'%L %Y,%J,%V,%p.',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\t.%\j %\V (%\Y) %\p%-\P\.',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%T.%M.%J,%V,%p,%Y.%X.',
    r'\\item{ %\G {\\bf %\t}, { \\it %\j }  %\V (%\Y) %\p}',
    r'%\4m,%\Y,%\j,%\V,%\p ',
    r'%g,%(y),%t,%j, %V,%p%-P',
    r'\\bibitem[%\2m%(y)]%{R} %\8.8l %\Y,%\j,%\V,%\p',
    r'\\bibitem%{%M%Y} %L %Y,\\textit%{Q} \\textbf%{V}, %p',
    r'\\item {%\12.12l} {%T} (%Y), %\J, %\V, %\p',
    r'%I,%T,%q %V,%p‚Äì%P (%Y). DOI: %d',
    r'%\I (%\Y), "\href{%u}{%T}", %\j, \textbf{%\V}, %\p',
    r'%3l,"%t",%J,%V,%p (%Y)',
    r'%z000 %T, %\8.3a, %J %\V,%\p %(Y) ',
    r'%l  %T  %J, %V, %p - %P',
    r'%\30L, %\Y,"%T", %\J, %\V, %\p',
    r'%g,%Y,%T,%q, %v,%p  ',
    r'\\bibitem%{R} %\8i: %\q \\textbf{%\V}, %\p (%Y)',
    r'%ZEncoding:UTF-8 %zn | %T | %A | %F | %J | %D | %W | %R',
    r'\\bibitem[%\3m%(y)]%{za1%y} %\l "%T,''%\Y,%\j,%\V,%\p ',
    r'\\bibitem%[N]{} %8a \ %Y,%j,%V,%P',
    r'%10I, %t. %j %V, %p-%P„ÄÄ(%Y)',
    r'\\bibitem{%\1H%\y} %\3l {\\em %\T} %\Y {\\em %\J} {\\bf %\V} %\p',
    r'%z0 <p>  %U %T <br> %G | %F cit%c %K |, %J, <b> %V, </b> %p (%Y) </p>',
    r'%\zn. %\l %\Y, "%\t'', {\\it %\J}, %\V, %\p. [%\c citations]',
    r'\\item %\l, %Y: %\T. {\\it %\J}, {\\bf %\V}, %\p',
    r'%Y %c',
    r'%5.5N: %T, %j {\\bf %V} (%Y), %p--%P',
    r'%4M (%y), %t, %q, %v, %p',
    r'%\(<li>)>15.15g %\(<a href=")>u\(">)  %">T\("</a>) %>q %>V%,>p%->P %(>D\(\)</li>)',
    r'%\t.%10I %Y,%j,%V,%\p.',
    r'@%W{%1h:%y,, author =  abstract = {%B}, } z75',
    r'\\bibitem%{R} %\10I %\Y.%\t.%\J %\V,%\p%-\P\.',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'%6 %l, %\(")t\(,") %q, %V, %p, %(Y).',
    r'http://www.ijltem.com/index.html',
    r'%1l\ %y\ %q\ %v\ %p-%p',
    r'\\bibitem[%\4m%(y)]%{R} %\8l {\it %T}, %\j,%\V,%\p (%\Y)',
    r'\\bibitem\{journal\} %\3i:%\q \\textbf\{%\V\}, %\p (%\Y)',
    r'%D',
    r'<br><br><br>%zn Author: <b>%5M</b> Title: <b>"%T"</b> <br> <b>Number of citations:</b> %c <br> <b>Year:</b> %y <br> <br> "%Q"  <br> <br>  <b>Abstract:</b> "%B" <br><br> <i>"%K"</i> <br> %U',
    r'%T|%L|%y|%q|%V|%p|%P|',
    r'%R  %2.2A, %T,  %J %v, %p-%P (%y)CITATIONS:%c  ',
    r'%\100za2, "%T", %Q (%Y)',
    r'%3.3G,%"t\(,") %q,%V,%p,%Y',
    r'%g %(Y) %T.%q,%V,%p-%P.',
    r'%u',
    r'%\G  "%\T," %\q, %\V, %\p-%\P.',
    r'\\bibitem[%\2m%(y)]%{R} %\l %\Y,%\(\\emph{ ) T\(}, ) %\j,%\V,%\p,%u.',
    r'\\item{} {\\bf  %\T  }  \\item[]%\8a\\item[] {\\sl %\J,{\\bf %\V }, %\p, (%\Y).}',
    r'%\10L, %\Y: %\T, %\J %\V,%\p%-\P, %\(doi:)\d\.',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p\P',
    r'%a %y, %q, %v, %p',
    r'%ZEncoding:UTF-8 %5.1l %T. %q, %V, %p-%P (%Y).',
    r'\\item %\3a %\Y,"%\T\,'' {\\it %\J}, %\V,%\p%\P\. \ewline(%\u)',
    r'\\bibitem[%\4m%(y)]%{R} %\3L %\Y,%\j,%\V,%\p',
    r'%L, "%F"',
    r'%99g "%T", %Q (%Y)',
    r'%8.8A %Y, "%T", %J, %V, %p',
    r'%z5000%G,%"T",%J,%Y,%V,%p-%P ',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%ZEncoding:ISO-8859-1 %\8L %\Y, %\j, %\V, %\p, "%\T"',
    r'\\bibitem{%\1H\:%\yab}"%\T\,'' %\7I,%\j {\\bf %\V}, %\p-%\P %(y).\\textrm{(E)}',
    r'%R %A %J',
    r'%Zencoding:utf-8 %t %a %y %q %v %p %D',
    r'%6.6g. %T. %j %Y;%V:%p-%P',
    r'\\bibitem[%\3m(%y)]{%R} %\10l %\(\\emph{)\t}, %\(\\emph{)\q} %\({\\bf )\v} %(\y) %\p %[\X]',
    r'\\bibitem[%y]{%za1%y} %\8l %\Y,%\j,%\V,%\p',
    r'%ZEncoding:UTF-8%z0%T. %a %Y, %J, %V, %p-%P%d ',
    r'\\bibitem %[%2m (%Y)]{}%20a\ %Y,%j,%V,%P',
    r'\\bibitem[%\4m%(y)]%{R} %\1000.1000l,%T,%J,%\V,%\p%(\Y)',
    r'%z132 \\bibitem[%\2m%(y)%\3m]%{R}  %\8.1g,%\Y,%\q,%\V,%p',
    r'%ZEncoding:TeX%ZHeader:"%----------"%\(\\subject{)T}%\(\oindent {\\bf Authors:} )\A%\(\oindent {\\bf Keywords:})\K%\(Arkhiv stuff: ) This is the arxiv site : http://xxx.lanl.gov/abs/%X %\(URL: )u X%\(Pub: )W%\(\oindent {\\bf Abstract:} )\B',
    r'%A, %D, %q, %V, %p, %t',
    r'%T \\ %\8l \\ %\J,%\V,%\p,%\Y',
    r'"%T", %L,%q,%V,%p-%P %(y)',
    r'%i %(y), %T,%q,%V,%p%-P\, doi:%d.',
    r'%T, %l, %\Y,%\q,%\V,%\p',
    r'%\5.3l %\Y,%\j,%\V,%\p',
    r'\\item %\8l %\Y,%\T,%\j,%\V,%\p',
    r'%T, %l %Y, %J,%V,%p',
    r'\\bibitem[%\4m%(y)]%{za1} %\400l %\Y, %t, %\j,%\V,%\p ',
    r'%I \\emph{{%T}} %q \\textbf{%V} (%Y), %p',
    r'3be9aec0ec',
    r'%L, %T, %q, %V, %p (%Y) ',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R} %\8.3g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%\4m%(y)]{\b\i\b:%R} %\8l, %\j,%\V (%\Y) %\p-%\P  doi:%\d',
    r'\\bibitem[%4m %(y)] %4.3l %t. %j,%V, %p,%P %(y)',
    r'http://www.travell.co/',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'"%T ","%A ","%D ","%J ","%V ","%p "',
    r'<li><a style="font-weight:bold; font-size:14pt" href="%u">%T</a><br>\%Y, %J, %v, %p - %c citations<p style="margin-left:25px;font-size:9pt">%G</p></li>");20- %c citations<p style="margin-left:25px;font-size:9pt">%G%',
    r'RIS',
    r'\\item %\g, \\emph{%\T}, %Y, %\q, %\p, %\V, %\c citations',
    r'%Zencoding:UTF-8 %D \t %W %T %N %D %Q',
    r'%\300I.\ewblock{%\T}. ewblock{\\em %\J}, %\V:%p--%P,%\Y,%\X.',
    r'%z000 \\item %\10.3N, %\Y, %"\T", [file: // \\underline{ %\q}]\\underline{ %\q}, % \V, % \p',
    r'%L, %Y, "%T", %q, %V, %p',
    r'\\bibitem[%\2m%(y)]%{R} %\g %(\Y) %\T.%\j %\V:%\p-%\P',
    r'%%%z132% T %%%u\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%3M (%Y)]{%za1%Y} {%10L} %Y, \\textit{%J}, %V, %p ',
    r'%ZEncoding:UTF-8%ZLinelength:119___________________________________________________________________________________________________%\(Autores\/res\ \(por\ orden\ de\ firma\):\ )g%\(Titulo:\ )TRef.\ x\ \ \ \Revista:\ \ %JClave:\ A \ \ \ \ \ \ \ \ \ \ \ \ \ \Volumen: %V \ \ \ Paginas, inicial:\  %p \ final:\  %P \ \ \ \ Fecha: %DEditorial\ (si\ libro\):Lugar\ de\ publicacion:',
    r'%\l, %\Y, %\T, %\J %\V, %\p',
    r'%\L,%Y.%T,%\J %V,%p.',
    r'\%I. \%T,%\({\\it )j\(}, )\%V\%(:)p,\%Y',
    r'\\item{} %\G,%Y,{\\sl %\t}, %q,\\underline{%V},%p, (cites %c)',
    r'%L (%Y) %t.%J %V,%p%-P.',
    r'\\bibitem[%\4m%(y)]%{\za1%y} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%A.%t.%J,%\V:%\p%-\P\, %D.%\u',
    r'\\bibitem%{R} %\10I {\\em %t}, {\\em %\j}, {\\bf %\V}, (%\Y)% \p',
    r'\\bibitem[%\8m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'%ZEncoding:TeX %z75\\item %M,%Y,%\(")T\('', )\{\\em %J\}, \{\\bf %V\}, %p--%P (%c citations)',
    r'<li><b>"%T''</b><br><i>%g %Y</i>, %J %v, %p-%P<br>"%T"<br>[<a href=%u>%X</a>]<p></li>',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{\za1\y} %\8.3g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%\2M%(y)]%{R} %\10i, %\t,%\j %\V,%\p%-\P (%\Y)\.',
    r'%ZEncoding:UTF-8 "%\T"%A, %\J %(\q), %\Y, %\V,%\p%-\P\.',
    r'\\bibitem[\\protect\\citename%{\1M} %y]%{R} %\1.1g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%\2m%(y)]%{R} %\l %\Y,%\(\\emph{ ) T\(}, ) %\j,%\V,%\p,%u.',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V:%\p-%\P',
    r'%G %Y. %T. %J %V:%p-%P.',
    r'%\12L, %\Y, %\T, %\j, %\V, %\p%-\P\.',
    r'%\5l %T,%J,%\V,%\p%(y)%z0',
    r'%R',
    r'%c %n',
    r'%z0%a%J,%Y:%V:%p-%P%T  ',
    r'%3.3I,%T,%J,%V,%p,%Y',
    r'%g,%\t,%J,%\V,%\p%-\P,%Y.',
    r'\\bibitem[%\2M%(y)]%{R} %\10i {\\em %\t}, %\j %\V,%\p%-\P\, %\Y.',
    r'%g, %Y, "%T'', %J, %V, %p%-P.',
    r'\\bibitem%{R}%\8.3l,%\q,\\textbf{%\V}, %\p (%y)',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R} %\8.3g,%\Y,%\q, %\V,%\p',
    r'%\i,\%T,%\J,%\V,%\p, %\Y',
    r'%L %Y, %J, %V, %p, "%T"',
    r'\\bibitem[%\({\\it )\2M} %(y)]%\{{}%I,%T%,%j,%v,%p-%P',
    r'\\item %\W,%\c,{\\em %\T}, %\8l %\Y,%\j,%\V,%\p.',
    r'%z0%R : %c : %y : %g',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'%ZLinelength:0 %ZEOL:"" %T, %G, %Y, %j, %V, %p',
    r'\\bibitem[\\protect\\citeauthoryear%{\1h} %{y}]%{%za1%p} %\8.3g,%\Y,%\q, %\V,%\p',
    r'"%T", %Y, %G, %J, %V, %p\-%P, DOI %d',
    r'\\bibitem %{%1H%y} %\3l %\t. %\J  %\V,%\p-%\P (%\Y)',
    r'%G (%Y), %T, %J %V, %p-%P, DOI:%d ',
    r'\\bibitem[]{} %\8l, %\Y,%\j, %\t, %\V,%\p ',
    r'\\bibitem[%\4m%(y)]{%1.1h%Y}%\8.3l %\Y,%\j,%\V,%\p',
    r'%8.8l, %\t, %\Y, %\q, %\V, %\p',
    r'\oindent %\8l %\Y%\t,%\j,%\V,%\p',
    r'%5.5N: %T, %j {\\bf %V} (%Y), %p--%P',
    r'\\bibitem%{%1m:%y} %\3l,"%\t'',%\j,vol. %\V,pp.~%\p--%\P, %\D.',
    r'"%L, %y, %q, %V, %p"',
    r'\\bibitem[\\protect\\citename%{\2m} %y]{%1h\_%R} %\8.3g, %\q, {\\bf %\V}, %\p (%\Y)',
    r'\\bibitem[%\4m%(y)]%{R} %\500l %\Y,%\T,%\j,%\V,%\p',
    r'\\bibitem%{R} %\8l: %\T. %\q, %\({\\bf )V\(}, ) %\p--%\P %(\Y)',
    r'\\bibitem{ }  %\10g %\Y \\textit{%\J} \\bf{%\V} %\p',
    r'%\i,%\T. %\q {\\bf %\V}, %\p-%\P (%\Y). \\ULurl{doi:%\d}',
    r'%8.1i, \"%T\", %q, %V %p \(%Y\) ',
    r'%\8.5g,%\Y,%\Q, %\V,%\p,%"\t"',
    r'<body> </p> %g, <i>%T</i>, %Q, %D %(X), %U </p> </body>',
    r'%\(\\bibitem[)\2m%\(()Y\(\)])%\({)r\(}) %\L %\Y, "%\T", %\J, %\V, %\p, doi:%\d',
    r'%3.3l,%c',
    r'%T %l %Y,%J,%V,%p',
    r'\%\l%99,  %Y.  {%\400T}. %\j,%\V,%\p',
    r'\\bibitem[%\2m%(y)]%{%1H%y} %\l %\t. %\Y,%\J,%\V,%\p%-\P',
    r'%R %c',
    r'\\bibitem%{R} %8l,  \ewblock {%T}, \ewblock %j  {\\bf %V}, %p (%Y).',
    r'%6.5l %>Y,%>q,%>V,%>p,  %>\"%>t%>\"',
    r'\\item %\4.4a %\Y, \\\\ \\emph{%\T}, \\\\ %\j,%\V,%\p\--%\P',
    r'\\item %\5I (%\Y). {\\bf %\t.} %\j %\V,%\p%-\P\.',
    r'%"T" %I %Y,%j,%V,%p%-P',
    r'\\bibitem[%\3m%(y)]%{\za1%y} %\5.3l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%ZLinelength:500%L,%y.%t.%J %V,%p---%P.',
    r'%d ***  %T ***  %\6.6l *** %\J *** Vol %\V ***  %C *** United Kingdom *** %D *** %\p - %\P *** yes *** peer reviewed publication *** http://arxiv.org/abs/%X   ',
    r'%L %Y.%t.%J %V,%p-%P.',
    r'%\8l %\Y,%\T,%\j,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,%\j,%\V,%\p',
    r'%D|%1N|%c',
    r'\\item %\30a %\Y,"%\T\,'' {\\it %\J}, %\V,%\p',
    r'\\reference \%l  %\t. %\j,%\V, \%p--\%P (\%Y)  %\u ',
    r'%8.8l, %\t, %\Y, %\q, %\V, %\p',
    r'\\bibitem[\\protect\\citeauthoryear%{\3m}%{y}]%{R} %\8.3g,%\Y,%\q, %\V,%\p',
    r'%i.%Y.%T.%J %V:%p%-P. ',
    r'\\bibitem{ } %\I, {\\it %\T}, %\j {\\bf %\V}, %\p (%\Y)',
    r'%L,%"T'',%y,%J,%V,%p',
    r'\\bibitem%{R} %\3i,%j %\V (%\Y) %\p',
    r'%\A,"%\T\,''  %\j, %\V,%\p (%\Y)',
    r'\\bibitem %{R} %\4l %\T %\J %\V, %\p - %\P (%\Y)',
    r'%\z120 \\item {\\it %\T} \\\\  %\l %\Y,%\j,%\V,%\p \\\\',
    r'%ZEncoding:TeX%ZHeader:"%----------"%\(\\subject{)T}%\(\oindent {\\bf Authors:} )\A%\(\oindent {\\bf Keywords:} )\K%\(Arkhiv stuff: )X%\(URL: )U%\(Pub: )W%\(\oindent {\\bf Abstract:} )\B',
    r'\\bibitem[%\2m%(y)]%{%za1%y} %\8l %\Y,\\textit{%\q}, %\V,%\p',
    r'%z80%N,%Y,%\(")T\(", )%J,%V,%p',
    r'\\bibitem[%\4m%(y)]%{R} %\3.3G %\Y,%\j,%\V,%\p ',
    r'%Zencoding:ISO-8859-1 %z0%g*%T*%Q*%D*%R*%u',
    r'\\bibitem{%\za1%\Y} %\I, %\Y,"%\T'',%\J %\V, %\p-%\P.',
    r'\\bibitem[%\2m%(y)]%{za1%Y}  %\8l %\Y,%\j,%\V,%\p',
    r'%z132 \\bibitem[%\2m%(y)%\3m]%{R} %\8.1g,%\Y,%\q,%\V,%\p',
    r'%\l %\Y "%T'' %\J,%\V,%\p',
    r'%ZEncoding:UTF-8 %ZLinelength:0 %50.3L %Y, %q %V, %p %t %u',
    r'<li><span class="pubtitle">%>T</span>, <span class="pubauthor">%>3.3G</span>, <span class="pubjournal">%>J</span>, v%V, p%p, %Y [%U]</li>',
    r'%\T, %\N, %Y, %\q, %V, %p--%P (%cc)',
    r'%\G,%\Y,\%T,%\j,%\V,%\p',
    r'%\O \& {\\it %\3l} (xx authors) %\Y,%\q  %\V,%\p\.  %T\. ',
    r'%\T. \ewblock{%\300I.}\ewblock{\\em %\J}, %\V:%p, %\Y,%\X. ',
    r'\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,%\j,%\V,%\p',
    r'\\item[] %\l %Y,\{\\em %\T}, %\j,%\V,pp%\p-\%P',
    r'\@%w{%R, \tAuthor = {%A}, \tYear = {%y}, \tTitle = {%T}, \tAbstract = {%\B}, \tJournal = {%j}, \tVolume = %V, \tPages = {%p--%P}, \tUrl = {%/u}}',
    r'\\item %\12.12N, %y, \"%\T\", \{\\em %\J\}, %\V\, %\p',
    r'%G %Y %T %J %V %p',
    r'%t, %\L, %\Y, %\J, %\V, pp.%\p%-\P ',
    r'%\3.3G,%Y,"%\T", %\q,%v,%p',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\j. %\V\:%\p',
    r'"%T", %Y, %G, %J, %V, %p\-%P, DOI %d',
    r'\\item {%\12.12l} {%T} (%Y), %\J, %\V, %\p',
    r'%ZEncoding:ISO-8859-1%N%T%q %v (%D)DOI: %dURL: %u',
    r'%z0%N (%Y) %\()T. %J %V\: %p-%P & %jIF & %c',
    r'\\bibitem[{{%\3m}%(y)}]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\4m%(y)] %\8l %\Y,%\j,%\V,%\p',
    r'%z0%\m, %\T, %D',
    r'%T%G%Y%J%,v%p',
    r'\\item %\12.12N, %y, \"%\T\", \{\\em %\J\}, %\V\, %\p',
    r'\\item {\\it %\T}\\\\    %\l %Y,%\q,%\V,%\p (%X)',
    r'<P>%&a %&Y, %&J %&c cites <A href=%"u">%&T</A>',
    r'%G (%Y), %T, %Q, %V, %p',
    r'%\5.3l, "%T",%\Y,%\J,%\V,%\p',
    r'%\8m, %\Y, "%T", %\j, %\V, %\p',
    r'%zn. %\8.3i,%\Y,%\q, %\V,%\p, %X: %T',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p\\tit{%\t}\\url{%u}\\abs{%\B}',
    r'%ZEncoding:UTF-8Nr. %zn.%u%A%TJournals: %J Date: %D',
    r'%z900%20a,%T,%J,%V,%p-%P (%Y). %c citations',
    r'%\8l %\Y, {\\it %\T}, %\J,%\V,%\p',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R} %\30g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%\2m%(y)]%{R} %\l %\Y,%\(\\emph{ ) T\(}, ) %\j,%\V,%\p,%u.',
    r'%3.3l,%Y,%q,%V,%p',
    r'%l %Y, %J v.%V, pp. %p-%P; "%T"',
    r'\\bibitem[\\protect\\citeauthoryear%{\1h et al.}%{y}]%{1h}  %\8.3g,%\Y,  \\textsl%{\T},  %\q, %\V,%\p',
    r'%z0@%W{%\2.2M-%y,   author   = {%\g},    title    = {%\t},    journal  = {%J},  %\(  volume   = {)v\(},)   pages    = {%p%\(--)P },    year     = {%y}, %\(  url      = {)\X\(},)   cited    = { today },   keywords = {                   } }',
    r'%A %(y) %T. %J, %\V,%\p ',
    r'\\bibitem[%\4m%(y)]%{1m%Y} %\5.3l %\Y,%\j,%\V,%\p',
    r'%ZEncoding:UTF-8%830.1i,%"T", %j, %V, %p (%Y)',
    r'\\bibitem{%\1H%\y} %\3l %\Y {\\em %\J} {\\bf %\V} %\p',
    r'%za1 et al., %T, %Y, %q, %V,  %p-%P  ',
    r'\\bibitem[%\4m%(y)]{%\4m%(y)} %\8l: %\T. %\j, %\V, %\p-%\P (%\Y) ',
    r'%\10L (%\Y) %\t. %\J %\V, %\p%-\P\.',
    r'%\8l "%\T'', %\Y,%\j,%\V,%\p',
    r'\\bibitem%{R} %\8l: %\T. %\j, {\\bf%\V}, %\p%-P (%\Y). DOI %\d',
    r'{%\1M}}{{%\1M}}{%\Y}]{}{%\8l} %\Y,%\j,%\V,%\p',
    r'\bibitem{} %1G %T / %I // %J --- %Y.--- NO %V.--- c. %p.',
    r'%ZEncoding:UTF-8%3.3G %Y,%J %V,%p-%P',
    r'%\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%\zn. %\l %\Y, "%\t'', {\\it %\J}, %\V, %\p. %\c citations',
    r'@Article{%M-%R, author = %"\5g", title = %"T", journal = %"J", year = %"Y", volume = %"V", pages = "%p%-P\", ADScitation = "\%\%%R\%\%",}',
    r'\\bibitem[%\2m%y]{%\za1%y} %\5.3l %\Y,%\j,%\V,%\p',
    r'%8l (%Y). "%t\(.)" %q,%V,%p.',
    r'\\bibitem%{R} %\8l \ewblock{%t}. \ewblock{ \em %j}, %\V,%\p,%\D',
    r'<li><a href="%u">%T</a></li><ul><li>%l %Y, %q, %V, %p</li></ul>',
    r'%L,"%T", %Y,%q,%V,%p-%P, %c',
    r'%5.1l %t.%q %v,%p-%P (%y).',
    r'%I, %T, %Y, %J, %V, %p',
    r'\\bibitem[\\protect\\citeauthoryear%{\3m}%{\2m} %{y}]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%\8.3g,%T,%\Y,%\q, %\V,%\p Number of citations: %\c ',
    r'\\bibitem%{R} %\10I {\\em %t}, {\\em %\j}, {\\bf %\V}, (%\Y)% \p',
    r'%N,%Y,%\(")T\(", )%J,vol %V%\(, page )p%\(-)P %(x).%\(")T\(", )',
    r'%\25l, %Y, %J, %\V, %\p, %"T"',
    r'%g, "%T", %q, %V, %p, (%Y).',
    r'\\bibitem[%\4m%(y)]%{za1%\Y} %\8l %\Y,%\q,%\V,%\p',
    r'\\bibitem[%\3m%(y)]{%\2M% y} %\6l %\Y,%\j,%\V,%\p',
    r'\\reference %I.%Y.%T.%J %V,%p%-P.',
    r'\\item{} %\90g, %Y, {\\em %T},\ %\j \ %\V %\p',
    r'\\item %\12.12N, %y, \"%\T\", \{\\em %\J\}, %\V\, %\p',
    r'\\bibitem[\\protect\\citeauthoryear{%\m}{{%za1} et~al.}{%Y}]{%za1%Y} %\8.3g,%\Y,%\j, %\V,%\p ',
    r'\\item %\10I %\Y.%\t.%\J %\V,%\p%-\P\.',
    r'%zn %\10.3g, %\Y, %"\T", % \q, % \V, % \p, ( %\c citations) ',
    r'%Zencoding:UTF-8%Zlinelength:512%g %y, %J %v,%p',
    r'\\item %\A: \\textit{%\T,} %\j,%\V,%\p %(y) (\\href{%u}{%\R})',
    r'\\bibitem[%\4m%(y)]%{\za1%y} %\8l %\Y,%\j,%\V,%\p',
    r'%N, %Y. %T. %J %V, %p-%P.',
    r'%N (%Y) %T. %J %V: %p-%P',
    r'\\bibitem{%1H%Y} %\4l,%t,%\j,{\\bf %\V}, %\p-%P,(%\Y)',
    r'%ZLinelength:500%50.1I (%y) %t. %J %V, %p--%P.',
    r'%g\: %y\, %q\,  %\({\\bf )V\(}, ) %p\.',
    r'%i.%Y.%T.%J %V:%p%-P.',
    r'%\8.1l %y, %q, %v, %p',
    r'\\bibitem[%\2m%(y)]%{%1H%y} %\l %\t. %\Y,%\J,%\V,%\p%-\P',
    r'<record>\t<citations>%c</citations>\t<year>%\Y</year>\t<author>%\1M</author>\t<journal>%j,%\V,%\p</journal>\t<keywords> %K </keywords>\t<title>%&T</title></record>',
    r'\\bibitem[%\4m%(y)]{%za1%ya} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem%{R} %\10.10i,%\j,\\textbf{%\V}, %\p (%Y). ',
    r'%\4m%(y)%{R} %\5.3l %\Y,%\j,%\V,%\p',
    r'{\\it %\3l} %\Y,%\q %\V,%\p\. %T\.',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%g,%Y,%q,%V, %p',
    r'%3.3G\, %q\, %v\, %p\, %y',
    r'%L, %Y, "%T", %q, %V, %p-%P',
    r'%ZEncoding:ISO-8859-2%z0%15.1L%Y%J%q%v%p%t%c',
    r'\\bibitem[\\protect\\astroncite%{\1h}{%y}]%{R} %\8.3g,%\t,%\j, \\textbf{%\V}, %\p (%\Y)',
    r'\\bibitem[%\2M%(y)]%{R} %\0i %\Y.%\t.%\j\\ %\V,%\p%-\P\.',
    r'%z0%l %"T\(,") %q,%V,%p%-P\, %(y).',
    r'\\item %\g, %\Y, "%\T'', {\\em %\J, }  {\\bf %\V,} %\p {--} %\P',
    r'\\bibitem[%\4m%(y)]%{R} %\T %\8l %\Y,%\j,%\V,%\p',
    r'%\10I,(%Y),%t,%J,%V,%\p%-\P',
    r'@%W{%R, author=%{\8.3g}, title="%\T", journal=%\q, year=%Y, volume=%V, pages={%p%-P }, }',
    r'\\bibitem[%\3m%(y)]{%\2M% y} %\6l %\Y,%\j,%\V,%\p',
    r'%\i "%\T,'' %j %V, %p%\(--)P (%y)',
    r'NN:bibcode:%\R  NN:authors:%\M  NN:citations:%\c  NN:abstract:%\B',
    r'%\I, (%\Y), "%\T", %\J, %\V, %\p-%\P\\',
    r'<li><a href="%>1.20u" > <strong>%>1.20T</strong></a>  <br> %>1.20M </li>   ',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\. %u',
    r'%z9999 %r | %4.3m | %t',
    r'\\ref [] "%\t,'' %\3a, %\y,  %\j, %\v, %\p',
    r'\\bibitem[\\protect\\citeauthoryear%{\1h et al.}%{y}]%{1h}  %\8.3g,%\Y,  \\textsl%{\T},  %\q, %\V,%\p',
    r'\$\\bullet$ %\A:  "%\T", %\Q %\Y',
    r'%60I (%Y) %T.%J,%V,%p%-P %d.',
    r'%\4m%(y): \%J, %\Y, %\V,%\p  ',
    r'%z1000\t%R\t%>T\t%>A\t%>F\tN\t%J\t%V\t%D\t%Y\t%p\t%P\t%>K\t%>O\t%q\t%C\t%u\t%x\t%X\t%>B \t2007-07-07 12:00:00\t',
    r'%j,%\V,%\p-%\P,%\2l , %\Y, %\T',
    r'\@%w{%R, \tAuthor={%\A}, \tYear = {%y}, \tTitle = {%T},\tAbstract ={%\B}, \tJournal = {%j}, \tVolume = %V,\tPages ={%p--%P}, \tUrl = {%/u}}',
    r'%5.3l %Y,%q,%V,%p',
    r'\\bibitem%{R}%\5G,%\t, \\textit{%\J}, %\V, %\p%-\P\  (%\Y) ',
    r'\\bibitem[%\4m%(y)]%{R} %\5.3l (%\Y), %T,  \\textit{%J %\V,} %\p --%P.',
    r'%L, %T, %J, %V, %p, %Y',
    r'%g "%T", %y, %J, %v, %p',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p,%\t',
    r'\\bibitem[%\2M%(y)]%{%1M%y} %\20I (%\Y), %\t,%J,%\V,%\p%-\P\.',
    r'%a%t%J,%V,pp%p-%P,%Y',
    r'%A,%Y,%Q,%S,"%T"',
    r'%z0%N (%Y) %\()T. %J %V\: %p-%P & %jIF & %c \\\\ \\hline',
    r'%z0%l %"T\(,") %q,%V,%p%-P\, %(y). %u',
    r'"%T,'' %\8l,%\J,Vol.\\ %\V,%\p (%Y)',
    r'\bibitem{%\za1]} %\6.3l %\Y,%\q,%\V,%\p',
    r'%10i,  {\\it %T },  %q {\\bf %V }  (%Y), %p  .',
    r'%\l %\Y,%T,%\J,%\V,%\p,%\u',
    r'%\o & {\\it %\3l} (x authors) %\Y,%\q %\V,%\p\. %\T\. ',
    r'%T. %g. %J, %V, %p, %Y ',
    r'%"T",\%A,\%J,\%v,\%p,\%y',
    r'%8l, %Y. %T,%J,%V,%p',
    r'\\bigskip {\\it %\M (%Y) }\\smallskip %\B',
    r'\\bibitem[%\4m%(y)]%{R} %\l %\Y, {\\it %\T}, %\j,%\V,%\p, doi:%\d',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,"%\T", %\j,%\V,%\p',
    r'\i{\\bf Title: %\t\\\\}{\\bf Authors}: %\3.3m\t%\r \\vspace\*{0.1cm}\\\\{\\bf Abstract:} %\B\\vspace\*{0.3cm}%%-----------------------',
    r'%ZLinelength:999%ZEncoding:Unicode<P>%>l,%y,<b>%t</b>,%U%J,%V,%p</a>',
    r'\\bibitem[%\2m%(y)]%{R} %\l %\Y,%\(\\emph{ ) T\(}, ) %\j,%\V,%\p ',
    r'{%\T}{%L6}{%\Y}{%\j}{%\V}{%\p}',
    r'\\item  %\88.3g,%\Y,%\q, %\V,%\p%-\P, "%\T''',
    r'\\item%\g \\\\\{\\bf %\t \}\\\\%\Q (%y)',
    r'%\A, "%\T", %J, %V, pp.%p-%P,(%Y)',
    r'%\8l %\Y,"%T,'' {\\em %\q},%\V,%\p',
    r'%A %y, %q, %v, %p, %T',
    r'%5.5l %(Y): %z050%\({\\em )T\(}, )%z050%J,%\({\\bf )V\(}, )%p\( \\\\)',
    r'%60.60l, %\t, %\Y, %\q, %\V, %\p ',
    r'%R,%I,%T%I (%Y), %T,%J,%V,%p, doi:%d.',
    r'%\8l %"\T" %\Y, % \j, % \V, % \p',
    r'%T,%\3.3l %\Y,%\j,%\V,%\p',
    r'\\bibitem{%za1%V%Y}%\5.1i, %T.  {\\it %J} {\\bf %V}, %p--%P (%Y). ',
    r'%\8l %"\T" %\Y, % \j, % \V, % \p',
    r'%G  %Y, %\J{%\V}{%\p}. %% {\\it "%\T''} ',
    r'\\bibitem[\\protect\\citeauthoryear%{\3h} %y]%{R} %\8.3g,%\Y,%\q, %\V,%\p',
    r'%D; %J; %c',
    r'\\item %\8l %\Y, %\T, %\j, %\V, %\p',
    r'%G, %T, %D %J, %V, %p-%P',
    r'\\bibitem{%\1H%Y} %\L,%\T,%\q,%\V,%\p%-\P (%\Y).',
    r'\\item %\l, \\textit{%T}, %Y %\j,\\textbf{%\V},%\p',
    r'\\item {\\em \\boldmath$\\ast$%\t}\\\\%\G (3 authors)\\\\\\htmladdnormallink{%\q {\\bf %\V} (%\Y) %\p }{%\u}',
    r'%\o \& {\\it %\3l} (xx authors) %\Y, %\j, %\V, %\p\. %\t\.',
    r'\\bibitem[\\protect\\citeauthoryear%{\3.1h} {%y}]%{R} %\8.3g,%\Y,%\q, %\V,%\p',
    r'%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'%Zencoding:utf-8 %t %a %y %J %v %p ',
    r'3f632c0ef1',
    r'\\bibitem[\\protect\\citeauthoryear{%1m}{%y}]%{\1h%y} %\8.3g,\\emph{%\T}, \\emph{%\q}, \\textbf{%\V}, (%\p)',
    r'%\(\`\`)%T\\\\  %\8l\\\\  %\J,%\V,%\p,%\Y',
    r'%\zn. %\l %\Y, "%\t'', {\\it %\J}, %\V, %\p. [%\c citations]',
    r'%ZEncoding:UTF-8 \\item %3a %y, %q, *%v* %p',
    r'%T XXXXX %A  XXXXX %D XXXXX %J XXXXX %V XXXXX %p  NNNNN',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R}%\8.3g\ewblock \\emph%{%\q%}, %\V,%\p,%\Y',
    r'\<li><p>%>6.3g\, %t\, \<i> %J\</i>\,\<b> %v\</b>\, %p\, (%y)\, \<a href = "http://xxx.lanl.gov/abs/%X\">%X\</a>\.\</p></li>',
    r'%I, %T, %\Y,%\Q',
    r'%Y %T %L %q %V %p %d',
    r'@Article{%M-%R, author = %"\5g", title = %"T", journal = %"J", year = %"Y", volume = %"V", pages = "%p%-P\", ADScitation = "\%\%%R\%\%",}',
    r'%7.7l %Y, %J, %V, %p  \t %u',
    r'%L (%Y) %t.%J %V,%p%-P.',
    r'\\bibitem[%\3m%(y)]{%\2M% y} %\6l %\Y,%\j,%\V,%\p',
    r'%10I (%Y), %t, %j, %V,%p-%P.',
    r'%\8.3g%\Y,%\q, %\V,%\p"%\T" (%c)',
    r'%\8.3g,%T,%\q, %\V,%\p,%\Y',
    r'\\bibitem[{%\4{m}%(y)}]%{R} %\8{l} %\Y,%\j,%\V,%\p',
    r'\\bibitem{%1H%Y} %\4l,%t,%\j,{\\bf %\V}, %\p-%P,(%\Y)',
    r'%\L',
    r'\\bibitem[%\4m%(y)]%{R} %\100l %(\Y). %T. %\j,%\V,%\p%-P',
    r'\\bibitem[%\2m%(y)]%{%za1%\Y} %\5.3l %\Y,%\j,%\V,%\p',
    r'%I, "%T", vol. %V, pp. %p-%P, %Y. ',
    r'\ *[:%z0%3.1m,%y,%t:]"Title:" %t"Authors:" %5.3G"ADSPage:" [%u] ',
    r'%z0%N (%Y) %\()T. %J %V\: %p-%P & %jIF & %c \\\\ \\hline',
    r'%5.3l %Y,%t,%J,%V,%p',
    r'%z0@%W{%\2.2M-%y,   author   = {%\g},    title    = {%\t},    journal  = {%J},  %\(  volume   = {)v\(},)   pages    = {%p%\(--)P },    year     = {%y}, %\(  url      = {)\X\(},)   cited    = { today },   keywords = {                   } }',
    r'\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,%\({\\em )T\(}, )%\j,%\V,%\p',
    r'\\bibitem[%\1h%y]%{R}{\\sc %\8.15g}, \\textit{%T.}, %J \\textbf{%V}, %p (%Y)',
    r'%\8l %\Y, %\q, %\V, %\p ',
    r'\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,%\j,%\V,%\p. "%T"',
    r'repman format',
    r'%\T. \ewblock{%\999I.}\ewblock{\\em %\J}, %\V:%p,%\Y,%\X.',
    r'%\8l  %\Y, "%\T'', %\q, %\V, %\p%-\P',
    r'\\item %\i,"%\T''\, {\\it %\J}, %\V,%\p, (%\Y).',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R} %\8.3g,%\Y,%\t,%\q, %\V,%\p',
    r'%T%J%D%%\v%\p,%\P',
    r'%I.%T.%J %V,%p-%P (%Y).',
    r'3e1c1d9752',
    r'%\4m%(y)%{R} %\5.3l %\Y,%\j,%\V,%\p,%\c, %T',
    r'Author, Date, Title, ',
    r'%ZEncoding:UTF-8 %z9999%10.1N,%Y,%\(")T\(", )%J,%V,%p-%P',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{R} %\8.3g,%\Y,%\q, %\V,%\p ',
    r'\\bibitem[%\2m%(y)]{%h%y}\\textsc{%\8l\\;} (%\Y).{\\em %T},%\j\\ %\V, %\p--%P\\ads{%>u}',
    r'\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,{\it %\j},%\V,%\p',
    r'%8.8l, %\t, %\Y, %\q, %\V, %\p',
    r'"%T" by %i, %J, Vol. %V, pp. %p%-P (%Y).',
    r'%G, %Y, %T, %q %V %p-%P',
    r'\\item %\8l %\Y, "%\t'', {\\it %\J}, %\V, %\p.',
    r'\\bibitem[%\4m%(y)]%{1H\%y} %\8l %\Y,%\j,%\V,%\p',
    r'%10l %Y, % J, v. %v, pp. %p-%P; "%T"',
    r'<tr><td>%>T<td>%>J<td>%>D<td>%>A<td>%>U',
    r'\Title: %T  \N_CIT: %c  \Year: %y  \Authors: %1L  \RefAuth: %H \Affil:  %1F',
    r'%R,%I,%T%I (%Y), %T,%J,%V,%p, doi:%d.',
    r'%20L, %Y,"%T", %J, %V, %p%-P.',
    r'\\bibitem[%\3m%(y)]{%\2M% y} %\6l %\Y,%\j,%\V,%\p',
    r'%\4L ,%J,%\V,%\p %\Y',
    r'<ref>{{cite journal  | author = %l | title = %t | journal = %J | year = %Y   | volume = %V   | pages = %p   | doi = %d   | bibcode = %r  }}</ref>',
    r'\\item %\N, %y, \"%\T\", \{\\em %\J\}, \{\\bf %\V\}, %\p',
    r'\\bibitem[\\protect\\citeauthoryear%{\1h}{ %y}]%{R} %\8.3g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%H(%Y)]%{R}%G\ %Y,%j,%V,%p',
    r'\\bibitem{%za1%y} %\3.3g.%t,%\j,%y,%\V:%\p--%P',
    r'\oindent %l, %Y, %j %V, %p',
    r'\\bibitem%{R} %\2.1i, \\emph{%\T}, %\Y, %\j, {\\bf %\V}, %\p [%\X]',
    r'[%\za1%\y]\\textit{%\T}, %\1g, %\y, %\q, %\V, %\p [Keck, P200, PTF]\\\\',
    r'\\bibitem[\\protect\\citeauthoryear%{\1h et al.}%{y}]%{1h}  %\8.3g,%\Y,  \\textsl%{\T},  %\q, %\V,%\p',
    r'\\bibitem[%\4m%(y)]%{\za1%\y} %\8l %\Y,%\j,%\V,%\p',
    r'%ZEncoding:UTF-8Header: Autores: %g  Titulo: %T  Ref %J  Clave: A  Volumen: %V  Paginas, inicial: %p  final: %P  Fecha: %D  Tipo de soporte: Revista  URL: %u  DOI: %d  Citas: %c',
    r'%\4A %\D %\T %\J  %\V %\c',
    r'%N. %Y. %T. %J %V, %p-%P',
    r'\\bibitem[%\4m%(y)]%{R}%\10.10l {\\it %T} %\Y,%\q {\\bf %\V}, %\p',
    r'\\bibitem\%[\2m(%\Y)]{%\2h\%Y} %\10l, %\Y, %\T, {\\it %\J}, %\V, %\p',
    r'%8l,  %T ,  %Y,%\j,%\V,%\p -- %\P',
    r'\\bibitem[%y]%{R} %\8l %\Y,%\j,%\V,%\p ',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %T %\J. v. %\V, p. %\p. %\Y.',
    r'\\bibitem%{R} %\5.3l %\t.\ {\\it %\j}\ {\\bf %\V}, %\p%-\P\ (%\Y).',
    r'[%\3m%(y)]%{R} %\8.50l %\Y,%\j,%\V,%\p,%\t',
    r'\\item %\N, %y, \"%\T\", \{\\em %\J\}, %\V\, %\p',
    r'%ZEncoding:UTF-8%>: %z0  %T;rus auth;%g;wos id;copus id;%Y;%K;%W;%J;ISSN;e-ISSN;ISBN;v.%V p.%p;%D;%d;wos;scopus;https://arxiv.org/pdf/%X;;;;;;;;;;;;;;;%R;%u',
    r'\\bibitem[%\4m%(y)]{%\za1%\Y} %8l %Y,%\j,%\V,%\p',
    r'%\8l %\Y,%\j, %t, %\V, %\p',
    r'%I, %T. {\\it %J} {\\bf %V}, %p-%P (%Y). doi:%d ',
    r'\\bibitem[%\4m%(y)]%{R} {\\it %T}, %\8l %\Y,%\j,%\V,%\p',
    r'%N',
    r'%\8.3g, "%\T", %\J,  %\V,  %\p, %\Y',
    r'%z132 \\bibitem[%\2%(y)%\3m]%{R}   %\8.1g,%\Y,%\q,%\V,%\ p      ',
    r'3be067a349',
    r'%ZEncoding:UTF-8 %ZLinelength:0 %8N, %Y.%T.%J %V,%p‚Äì%P.',
    r'{\\it %\3l} %\Y,%\q %\V,%\p\. %T\.',
    r'\\bibitem%[N]%{R} %2l %Y,%j,%V,%p',
    r'\\mynth%{\T}%{\m}%{\Y}{%\q,%\V,%\p}',
    r'%ZLinelength:500%L,%y.%t.%J %V,%p---%P.',
    r'%z0%1M,%Y,%q%,V,%p,%T',
    r'%T %\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,%\j,%\V,%\p',
    r'%6.6a,"%T", %J,Vol. %V,%D,pp. %p%,P.',
    r'\\bibitem[%1M \\etal\\ %(y)]%{R}{%\5.3l } %Y,\\textit{%\J},%\V,%\p',
    r'%z555%A, %\Y, %\q,%\V,%\p',
    r'\\bibitem[\\protect\\citeauthoryear{%\4m}%{y}]%{y} %\4.3l %j %\(\\textbf{ )V\(}, ) %p %(y).',
    r'%3l %Y, %q, %V, %p',
    r'%G, %T, %Y %q, %V, %p-%P.',
    r'%ZEncoding:UTF-8%\ \\item \%1G \ (%Y), \ "%T", \ %J \ \{\bf\%V\}, \ \%p \ \ \ \ ',
    r'%8l %Y,%T,%q,%V,%p',
    r'%ZEncoding:UTF-8\%N,%Y,\"%T\", %q,%v,%p. (%c citations)',
    r'%% %T\\bibitem[%\4m%(y)]%{R}%\8l %\Y,%\j,%\V,%\p',
    r'%5a %T. %J %V, %p-%P %(Y)',
    r'%l %Y,"%t", %J, Vol. %V, pp. %p-%P ',
    r'\\item %\T (%\8i) %\Y,%\j,%\V,%\p',
    r'\\bibitem[\\protect\\citeauthoryear%{\4m}%{y}]%{R} %\1.99l %\Y,%\J,%\V,%\p',
    r'%ZLinelength:9999%\g?%\F;',
    r'%z0 %3.3A (%Y) "%T" %q, %V, %p * * %c',
    r'%\l %\Y,%\J,%\V,%\p',
    r'%{R} %\8l %\Y, "%T,'' %\j,%\V,%\p',
    r'%T  %100l %Y,%J,%V,%\p',
    r'%12.12N,%Y,%T", %q,%V,%p ',
    r'\\bibitem[%\4m%(y)]%{R} %\30.3l %\Y,%\j,%\V,%\p',
    r'%ZLinelength:500%L,(%y) %t.%J %V:%p-%P',
    r'\\bibitem[%\4za3%(y)]{%za1%y} %\8l %\Y,%\j,%\V,%\p',
    r'%3.1a %y,"%T," %j,%v,%p',
    r'\\bibitem{} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem[%\2m%(y)]%{%1H%y} %\5.3l %\Y,%\j,%\V,%\p',
    r'%l %Y, %q, %v, %p, %T. ',
    r'%10.1g %Y %q %V %p%-P  ',
    r'\\item %\12.12N, %y, \"%\T\", \{\\em %\J\}, %\V\, %\p',
    r'<P>%&l, %Y, %q, %v, %p<br><i>%t</i>',
    r'%ZEOL:"\\end{description}"%ZEncoding:TeX%\(\\begin{description}\\item[)zn\.]%\({\\it )T\(.}  )%I%\(, )Y%\(, )q%\(, )V%\(, )p%\(\\,--\\,)P\.',
    r'\\i %T, %A: \\i %T,\\i0%q,%V,%p %(y)\\',
    r'%z132 \\bibitem[%\2m%(y)%\3m]%{R} %\8.1g,%\Y,%\q,%\ V,%\p',
    r'%I,%J,\%Y,%V,%p, "%T"',
    r'%R %m',
    r'Reference:  %\(Author: )L  %\(Title: )\T  %\(Journal: )J  %\(Year: )Y  %\(Volume: )V  Pages: %P%\( - )p  %\(URL: )u  %\(Doi: )d',
    r'% \\bibitem%{R} %\10I, {\\bf %\t}, %\j %\V,%\p%-\P\, %\Y.',
    r'%ZEncoding:ISO-8859-1%z130Title:      %TAuthor(s):  %4.3AReference:  %QURL:        %uPubl. date: %D',
    r'%\1000.3l %\Y,%\j,%\V,%\p',
    r'\item  %\7.5l %\Y.%\t.%\j %\V,%\p.',
    r'www.prpinjectionmd.com',
    r'\\bibitem[\\protect\\citename%{\1h} %y]%{\1h%\Y} %\8.3g,%\Y,%\q, %\V,%\p ',
    r'%zn %c',
    r'"\\emph{%\T}'', %\l,%\y,%\q,%\V,%\p',
    r'%L "%T" %Y,%J,%V,%p %u',
    r'%N,%Y,\"%T\", %q,%v,%p.',
    r'%z000%zn. %\t%\8.8g|%y,%\q,%v,%p',
    r'\\bibitem[\\protect\\citeauthoryear{%\m}{%\3m}{%\y}]{%\za1%\y}',
    r'/*AUTHORS*/ %G/*TITLE*/ %T/*CITATIONS*/ %c/*DATE*/ %D/*JOURNALLONG*/ %J/*REFERENCE*/ %Y, %q, vol. %V, pp. %p%-P /*REFCODE*/ %R/*CATEGORY*/ %W/*END*/',
    r'%ZEncoding:UTF-8%z0 bibitem{}%35.35g:  %T, %q, %V, %p, (%D)',
    r'\\bibitem[%\4m] %I, %j,  %\({\bf )V\(}, ) %p, (%Y)',
    r'\\bibitem{%\1H\:%\yab}"%\T\,'' %\7I,%\j {\\bf %\V}, %\p-%\P %(y).\\textrm{(A)} ',
    r'\%z200(%\za1%\R)%\T\.pdf',
    r'%\T,%\6za2, %\Y,%\J,%\V,%\p [%\c]',
    r'\\bibitem%{%za1%y} %\3i, \\textit{%\J}, \\textbf{%\V}, %\p (%\Y)',
    r'\ref %{\8.8g [\\protect\\citename%{\1h} %y]%{R} %\8.3g,%\Y,%\q, %\V,%\p\\',
    r'\\item %\l %\Y,%\j, \\textbf%{\V},  %\p',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'\\item  %\8.8l, \\textit{%\t}, %y, %j, %v, %p',
    r'@%W{',
    r'\\bibitem[%\2M%(y)]{%N%y}%N, %Y.%T,%J,%V,%p-%P',
    r'%z132 \\bibitem[%\2m%(y)%\3m]%{R}   %\8.1g,%\Y,%\q,%\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R}  %\8l %\Y,%T,%\j,%\({bf )V\(}, )%\p%-\P',
    r'\\bibitem[%\4m%(y)]%{R} %\8l "%\T," %\Y,%\j,%\V,%\p',
    r'\\bibitem%{za1} %g %\J,%\V:%\p-%\P %(\y)',
    r'\\hangpar%\i:{\\em %t},%\J %\V,%p,%\Y',
    r'\\item \href{%u}{%\R} %\G: \\textit{%\T,} %\j,%\V,%\p %(y)',
    r'%T\t%J\t%D\t%A%z0',
    r'\\begin{publist}{%T}%\I,%\j %\V,%\p,(%Y).\\end{publist}',
    r'\\item %\8.3g,\\emph{%\t}, %\Y,%\q, %\V,%\p (%\c cites)',
    r'%N, %T, %J, %V, %p-%P (%Y)',
    r'{\\it %\3l} %\Y,%\q %\V,%\p\. %T\.',
    r'%>J %>V,%>p,%>Y%>100.1I \  \\bibitem[%\4m%(y)]%{%za1%Y} %\15l %\Y,%\j,%\V,%\p  \\item %\15l %\Y,%\J,%\V,%\p  %\L:%"\t". \%q,%\V,%\p %(\y)',
    r'%L "%T" %Y,%J,%V,%p %u',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p \t',
    r'%z0 %3.1A (%Y) "%T" %q, %V, %p \t %c',
    r'%\O \& {\\it %\3l} (xx authors) %\Y,%\q %\V,%\p\. %T\. ',
    r'\\bibitem[%\2m%(y)]%{R} %\8l, "%\T,'' %\j\\ {\\bf %\V}, %\p (%\Y).',
    r'\\bibitem{%\1h:%y} %\I,%\j {\\bf %\V},%\p (%\Y).   %\T  %\X',
    r'\\bibitem[%\4m%(y)]%{R} %\5.3l %\Y,%t, %\j,%\V,%\p',
    r'\\bibitem[\\protect\\citeauthoryear%{\1h}%{y}]%{R} %\8.3g,%\Y,%\q, %\V,%\p, %\T',
    r'\\arabic{counter}.\\cbskip\\pubf{%\t} {%\g %\Y.%\q %\V,%\p%-\P\.}',
    r'\\bibitem%{R} %\5l %\t.%\J.%\V,%\p-%\P %(\Y)',
    r'%n.150 %N, %Y, %T, %q, %V, %p',
    r'%Zencoding:UTF-8 %A, "%T", %J,%V, pp. %p-%P, (%Y)',
    r'\\item[]  %\l %Y,\{\\em %\T}, %\j,%\V,pp%\p-\%P',
    r'%G,%(Y). %T.%J,%V,p. %p-%P , doi:%d.',
    r'\\reference%{R}%\8l %\Y, \`\`%\t\", %\j,%\V,%\p',
    r'%25M (%\Y) "%\t''.{\\em %\J %\V}, %\p%-\P\.',
    r'\\bibitem[%2M, %y]{} %4M, %y, %\( \\textit{){j\(},) %\()V\(, )%p',
    r'\\refs %3G:%J,{\\bf %\V}, %p (%Y)',
    r'%B',
    r'\\item %\a,  %\Y, %\j,%\V,%\p, "\\textit{%\T}, link:\\\\ %\u  ',
    r'%ZEncoding:UTF-8  %2.2G (%\Y). "%\t"  %\J, %\V, %\p ',
    r'%10I %Y.%t.%J %V,%p%-P. ',
    r'\\bibitem{} %5.3l %t. %j,%V,%p (%Y).',
    r'EndNote format (UTF-8)',
    r'\\bibitem{%\1H\:%\yab}"%\T\,'' %\7I,%\j {\\bf %\V}, %\p-%\P %(y).\\textrm{(A)} ',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\y,%\J %\V,%\p',
    r'Hacked By Ahooraxx Hacked By Ahooraxx Hacked By Ahooraxx Hacked By Ahooraxx Hacked By Ahooraxx',
    r'\bibitem[Lee Hwanhee \& Magara(2014)]{2014PASJ...66...39L} Lee, Hwanhee, \& Magara, T.\ 2014, \pasj, 66, 39 ',
    r'\\bibitem[%\2m%(y)]%{%1H%y} %\8l %\Y,%\j,%\V,%\p',
    r'%l, %Y, %t, %J, %v, %p-%P',
    r'\\bibitem[\\textit{%\4m}%(y)]%{R} %\L (%\Y), %\T,%\J,%\V,%\p-%\P,\\doi{%\d}',
    r'%T, %A, %J %Y, %V, %p',
    r'%3m %R "%T"',
    r'\\item %1.1a %Y, %q, %V, %p: {\\it %T}  ',
    r'\\startit %\za1%z999 \\startauth%\g \\endauth%D %q %W %V %p%c \\endit',
    r'%G; %T; %J; %V; %p (%Y) ',
    r'%ZEncoding:ISO-8859-2 %z0 %a (%Y): "%T", %J, %V, %p',
    r'%4.3G,%y "%T\(,") %q %v,%p (%c citations)',
    r'\\item \5.3l %\Y,%\t,%\q,%\V,%\p',
    r'\\bibitem[%\2m%(y)]%{za1%y} {%\5.3l}, \ewblock %\Y,%\q,%\V,%\p',
    r'%I,%t,%\j,%V,(%Y),%p-%P',
    r'"%T'', %Y, %\N, {\\it %J}, {\\bf %V}, %p.',
    r'%T By %8.1i %q \(%Y\) %V %p ',
    r'%"T", %l,%Y,%J,%V,%p%,d',
    r'%A, %y, %q %v, %\p',
    r'%\8.3g %\Y %T,%\J, %\V,%\p',
    r'%L, %Y, "%T", %J, %V, %p-%P',
    r'%G,"%T",%Q,%y ##',
    r'\\item %\5.3l %\Y,%\({\\em )T\(}, )%\j,%\V,%\p',
    r'%Zencoding:UTF-8%A,%Y,"%T", %J,Vol. %V,pg. %p',
    r'\\bibitem[%\3m%(y)]%{1H:%y} %\8l \\pub%{\j}%{\V}%{\p}%{\T}',
    r'%d',
    r'%A %"T" %J %V %(Y): %p-%P. ',
    r'\\bibitem[%\2m %y]%{R} %\l %\Y,\\textit{%\J}, %\V,%\p',
    r'"%\T"  %\8i {\it %\j} {\bf %\V}, %\p (%\Y) ',
    r'%G (%Y), %j, %V, %p , %c ',
    r'%g, "%t", %y, %J, %v, %p, [%c] ',
    r'%za1_%\T_%\q_%\y',
    r'%I (%y), %T, %J, %V, %p-%P, doi: %d.',
    r'\\bibitem[%\2m%(y)]%{R} %\500.500l %\Y,"%\T", %\j,%\V,%\p',
    r'\\bibitem[%\3m%(y)]%{\1m%(y)} %\8l %\Y,%\j,%\V,%\p',
    r'%G (%Y) %T. %Q',
    r'%7g %y.%T %J %V:%p--%P',
    r'Title: %tAuthor: %gCites: %cJournal: %JDate: %dVolume: %vPages: %p-%PLink: %uCategory: %WFull: %Q',
    r'%f',
    r'%G "%T." %J, %Y.',
    r'\\bibitem%{R} %\l {\\it"%\t"}, {\\bf %\j}, %\V,%\p,%\Y',
    r'%\5i,%\j,%\V,%\p (%\Y)',
    r'%3g "%t", %\(<i>)\J\(</i>), %\V (%\y\): %\p%-\P.',
    r'\\item{%\4.1a: %\t \\it %\J \\rm %(y) \\bf %\v \\rm %p%--P.}  %\(\\href{http://dx.doi.org/)d\(}{DOI}) %\(\\href{http://arxiv.org/abs/)X\(}{ArXiV})',
    r'\\bibitem[\\protect\\citeauthoryear%{\1h et al.} {%y}]%{\1h%y} %\3.3g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%\2M%(y)]%{R} %\10I %\Y.%\t.%\j %\V,%\p%-\P\.',
    r'\\bibitem[\\protect\\citeauthoryear%{\h}{%y}]%{za1_%\y} %\8.3g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%\3.m %y]{%za1%Y} %\3.m,%y,\\textit{ %\q},%v,%p',
    r'%\t %\3.3i %q %v, %p (%y)',
    r'%\10I %\Y,%\t. // %\j, Vol. %\V,%\p%-\P\, cituotas %\c.',
    r'\\bibitem[]{} %5.3N %y,%q,%v,%p',
    r'%ZEOL:" " %z000 %zn  \t  %za1  \t  %Y  \t  %c  \t  %q  \t  %T  \t  %g  \t  %F \t %k ',
    r'\\bibitem%{R} %\8.3g,%\Y,%\q,%\V,%\p, %\T,%\"citations\(2013/11/27\):%\c',
    r'\\bibitem[%\4m%(y)]%{R} %\8l "%T'', %\Y,%\j,%\V,%\p',
    r'%z0, %A (%Y), "%T", %J, %V, %p-%P',
    r'\\item  %\l %\T %\Y,%\j,%\V,%\p (%c citations)',
    r'\\bibitem[%\2m%(y)]\{%za1%y} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem{}%\4l %\Y, %\T, {\\it %\q}, {\\bf %\v}, %\p',
    r'%5.3N %Y.,%t,%J,%V,%p-%P',
    r'\\bibitem[%\3M(%y)]{%\1h%y} %\8.3g,%\Y,%\q, %\V,%\p',
    r'\\bibitem[%\4m%(y)]%{R} %\8l %\Y,%\j,%\V,%\p',
    r'\\bibitem%[\2m%(y)]{%2m\:%y} %% %{R} %\8l %\Y, "%\T'', %\j,%\V,%\p',
    r'%R',
    r'%5.5I %Y.%t.%J %V,%p%-P.',
    r'%\>%\T%\Y%\U%\p %\P',
    r'\\bibitem[%\4m%(y)]%{R} %\8G %\Y,%\j,%\V,%\p',
    r'%ZEncoding:TeX %z75\\item %N,%Y,%\(")T\('', )\{\\em %J\}, \{\\bf %V\}, %p--%P (%c citations)',
    r'%5.5a, %Y, %q, %V, %P',
    r'%\c',
    r'%N,%Y,%\(")T\(",  )%Q',
    r'%8l, %T, %J, %V, %p, %d, %Y.\t%u',
    r'%ZEncoding:TeX %z75\\item %N,%Y,%\(")T\('', )\{\\em %J\}, \{\\bf %V\}, %p--%P (%c citations; journal impact factor XX)',
    r'\\item %\N, %y, \"%\T\", \{\\em %\J\}, %\V\, %\p',
    r'\\bibitem[%\2m%(y)]%{R} %\8l "%T",%\Y,%\j,%\V,%\p',
    r'%\zn.%\I %\Y, ‚Äò‚Äô%t‚Äù,{\\it %\J}, %\V, %\p. ',
    r'\\bibitem[%\1m%(y)]%{R} %\8l , \\emph{%T},  \\ %Y,%\j,%\V,%\p',
    r'\\bibitem[%\2m,%y]{%1m%y}%5.g \%(y). %t,\\emph{%J}, %v, %p-%P',
    r'Za:100'
]


